<a href="https://colab.research.google.com/github/Shubham-Das-Coder/Important_Python_Libraries_For_Machine_Learning/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

*Lsit Vs Numpy - Time Taken*

In [2]:
from time import process_time

*Time Taken By A List*

In [3]:
python_list=[i for i in range(10000)]

start_time=process_time()

python_list=[i+5 for i in python_list]

end_time=process_time()

print(end_time-start_time)

0.0018619699999999906


In [4]:
np_array=np.array([i for i in range(10000)])

start_time=process_time()

np_array+=5

end_time=process_time()

print(end_time-start_time)

0.000431854999999981


*Numpy Arrays*

In [5]:
list1=[1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [6]:
np_array=np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [7]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [8]:
a.shape

(4,)

In [9]:
b=np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [10]:
b.shape

(2, 4)

In [11]:
c=np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


*Initial Placeholders In Numpy Arrays*

In [12]:
x=np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [13]:
y=np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [14]:
z=np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [15]:
a=np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [16]:
b=np.random.random((3,4))
print(b)

[[0.03125315 0.04609354 0.94039463 0.4588007 ]
 [0.76642652 0.49578057 0.07126404 0.072624  ]
 [0.02984586 0.04732825 0.45816163 0.65318603]]


In [17]:
c=np.random.randint(10,100,(3,5))
print(c)

[[42 17 20 52 95]
 [65 67 43 72 24]
 [35 93 63 69 43]]


In [18]:
d=np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [19]:
e=np.arange(10,30,5)
print(e)

[10 15 20 25]


In [20]:
list2=[10,20,30,40,50]

np_array=np.array(list2)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

In [21]:
c=np.random.randint(10,90,(5,5))
print(c)

[[72 14 43 75 40]
 [35 41 72 13 16]
 [20 48 85 63 83]
 [73 51 14 33 59]
 [72 46 23 33 48]]


In [22]:
print(c.shape)

(5, 5)


In [23]:
print(c.ndim)

2


In [24]:
print(c.size)

25


In [25]:
print(c.dtype)

int64


*Mathematical Operations On A Numpy Array*

In [26]:
list1=[1,3,5,7,9]
list2=[2,4,6,8]
print(list1+list2)

[1, 3, 5, 7, 9, 2, 4, 6, 8]


In [27]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))
print(a)
print(b)

[[3 0 4]
 [3 3 6]
 [0 3 2]]
[[11 18 17]
 [17 10 14]
 [16 10 18]]


In [28]:
print(a+b)

[[14 18 21]
 [20 13 20]
 [16 13 20]]


In [29]:
print(a-b)

[[ -8 -18 -13]
 [-14  -7  -8]
 [-16  -7 -16]]


In [30]:
print(a*b)

[[33  0 68]
 [51 30 84]
 [ 0 30 36]]


In [31]:
print(a/b)

[[0.27272727 0.         0.23529412]
 [0.17647059 0.3        0.42857143]
 [0.         0.3        0.11111111]]


In [32]:
c=np.random.randint(0,10,(3,3))
d=np.random.randint(10,20,(3,3))
print(c)
print(d)

[[7 2 5]
 [1 0 3]
 [8 7 3]]
[[18 17 14]
 [11 17 13]
 [15 14 19]]


In [33]:
print(np.add(c,d))

[[25 19 19]
 [12 17 16]
 [23 21 22]]


In [34]:
print(np.subtract(c,d))

[[-11 -15  -9]
 [-10 -17 -10]
 [ -7  -7 -16]]


In [35]:
print(np.multiply(c,d))

[[126  34  70]
 [ 11   0  39]
 [120  98  57]]


In [36]:
print(np.divide(c,d))

[[0.38888889 0.11764706 0.35714286]
 [0.09090909 0.         0.23076923]
 [0.53333333 0.5        0.15789474]]


*Array Manipulation*

In [37]:
array=np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[9 6 8]
 [3 5 3]]
(2, 3)


In [38]:
trans=np.transpose(array)
print(trans)
print(trans.shape)

[[9 3]
 [6 5]
 [8 3]]
(3, 2)


In [39]:
trans2=array.T
print(trans2)
print(trans2.shape)

[[9 3]
 [6 5]
 [8 3]]
(3, 2)


In [40]:
a=np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[9 2 2]
 [9 8 6]]
(2, 3)


In [41]:
b=a.reshape(3,2)
print(b)
print(b.shape)

[[9 2]
 [2 9]
 [8 6]]
(3, 2)
